### PR TITLE
Fix Recalculating order on changing FK on order_with_respect_to

### PR DESCRIPTION
**Pull request by Speedy1991**
Fix for #198 
I can provide some tests if you tell me where to place them

### CODE REVIEW

**Comment by caspervk** [comment]
What about the ordering of the objects with the old FK? Will there be a gap where the changed object was? If so, would calling `foo.bottom()` in the save method before changing the FK fix this issue?

**Comment by Speedy1991** [comment]
Thanks for the quick reply @caspervk !

Looking at the failed tests I don't think my PR will fix the issue

> What about the ordering of the objects with the old FK? Will there be a gap where the changed object was? 

yes - but as far I remember, this framework doesn't care about gaps?

> If so, would calling self.bottom() in the save method before changing the FK fix this issue?

Maybe - Can you explain a bit more? Do you mean to first check the `with_respect_to` field and handle this case completely different from the current save method?

**Comment by caspervk** [comment]
Consider four objects:

| FK | Object | Order |
|----|--------|-------|
| 1  | A      | 0     |
| 1  | B      | 1     |
| 1  | C      | 2     |
| 2  | D      | 0     |

We want to move object B to FK=2. After the move the table will look as follows:

| FK | Object | Order |
|----|--------|-------|
| 1  | A      | 0     |
| 1  | C      | 2     |
| 2  | D      | 0     |
| 2  | B      | 1     |

Where we notice that this pull request has fixed the issue under FK 2. However, there is now a "gap" between the two objects under FK 1. My idea was to first call `self.bottom()` in the `save()` method before changing the FK field, so as to create this table:

| FK | Object | Order |
|----|--------|-------|
| 1  | A      | 0     |
| 1  | C      | 1     |
| 1  | B      | 2     |
| 2  | D      | 0     |

and then use the updated code from this pull request to arrive at the final table:

| FK | Object | Order |
|----|--------|-------|
| 1  | A      | 0     |
| 1  | C      | 1     |
| 2  | D      | 0     |
| 1  | B      | 1     |

But if the framework indeed doesn't care about gaps, as you say, then I guess it doesn't matter 😃

**Comment by caspervk** [comment]
I had a problem using `OrderedTabularInline` in the admin with these changes. It would initialise all related objects, calling the new `__init__` function and setting `self._original_order_with_respect_to_fks` correctly.
However, as a last step it also initialised an object with all fields to `None` for some reason. This turned out to crash the admin rendering, as calling `self.rel` (for some related object `rel`) would throw an `RelatedObjectDoesNotExist` exception (note that `self.rel_id` is still defined in this scenario).

I fixed this by only setting `_original_order_with_respect_to_fks` in init if `self.pk is not None`. You could probably also check `if getattr(self, self.order_field_name) is None` -- not sure which is better.

Lastly, I also changed the three `{getattr(self, name) for name in self.order_with_respect_to}` to `self._get_order_with_respect_to()`.

Other than this small issue, this pull request fixes exactly the problem I was facing. Thank you very much @Speedy1991!

**Comment by imomaliev** [comment]
Hi could rebase and provide test?

**Comment by caspervk** [comment]
Thank you for updating the repo today @imomaliev -- especially the `bulk_create` is very handy.

I am using the following changes locally to achieve the behavior of this pull request in the new v3.2.0. The `self.pk` checks are because of the issues discussed in https://github.com/bfirsh/django-ordered-model/pull/199#issuecomment-509219595.

```diff
--- ordered_model/models.py	(revision f70318cc6a28c6382331d75a69c3d9f1f3498d59)
+++ ordered_model/models.py	(date 1562759870940)
@@ -66,6 +66,11 @@
     class Meta:
         abstract = True
 
+    def __init__(self, *args, **kwargs):
+        super().__init__(*args, **kwargs)
+        if self.pk is not None:
+            self._original_order_with_respect_to = self._get_order_with_respect_to()
+
     def _get_class_for_ordering_queryset(self):
         if self.order_class_path:
             return import_string(self.order_class_path)
@@ -117,10 +122,12 @@
         return self.get_ordering_queryset().below(self).first()
 
     def save(self, *args, **kwargs):
-        if getattr(self, self.order_field_name) is None:
+        if getattr(self, self.order_field_name) is None \
+           or (self.pk is not None and self._get_order_with_respect_to() != self._original_order_with_respect_to):
             order = self.get_ordering_queryset().get_next_order()
             setattr(self, self.order_field_name, order)
         super().save(*args, **kwargs)
+        self._original_order_with_respect_to = self._get_order_with_respect_to()
 
     def delete(self, *args, **kwargs):
         qs = self.get_ordering_queryset()

```

**Comment by Speedy1991** [comment]
> Hi could rebase and provide test?

Oh sorry, I lost touch to this PR. I didn't use this framework for nearly one year, so I'm not up to date with the current master branch.
If this is still bug, I can dig into it and provide some tests

**Pull request closed without merging**
