### PR TITLE
Add drf serializers

### PR DESCRIPTION
**Pull request by shuckc**
Attempt to integrate the DRF serializers mentioned on issue #251 contributed by @Schwankenson and @joshuadavidthomas into our test coverage and documentation. I'm aware the DRF test case doesn't query the ordered field yet - this is work in progress.

### CODE REVIEW

**Comment by joshuadavidthomas** [comment]
I have the test suite I used in my application that I can provide as an example, if need be. It's pretty straightforward.

**Comment by shuckc** [comment]
There's quite a serious shortcoming in the result I found when writings tests: if you inherit our default `order` field, it is set as `editable=False` (in `ordered_model\models.py:317`). This causes the parent DRF `serializers.ModelSerializer` to strip out any post/patch data for that field, so it never makes it into the `validated_data` set, therefore the re-ordering hooks in `OrderedModelSerializer` do not fire.

I'm guessing in your application you are defining your model on top of `OrderedModelBase` and therefore can set the ordering field as writable?

We might need to intercept the iteration of fields in ModelSerializer and set the field back to writable.

**Comment by shuckc** [comment]
This seems to work well enough:

    class OrderedModelSerializer(serializers.ModelSerializer)
    ...
    def get_fields(self):
        order_field = self.get_order_field()
        d = super().get_fields()
        for name, field in d.items():
            if name == order_field:
                if field.read_only:
                    d[name] = fields.IntegerField()
        return d

**Comment by joshuadavidthomas** [comment]
> I'm guessing in your application you are defining your model on top of `OrderedModelBase` and therefore can set the ordering field as writable?

Yep, you nailed it. I never had to consider the other use case, so I didn't run in to any fields with `editable=False`.

**Comment by shuckc** [comment]
I've amended the tox builds to try a couple of DRF versions, plus upstream so we should see if we break backwards, or are broken upstream. Will merge this as seems a good starting point.

**Pull request merged**
